#+LATEX_HEADER: \usepackage[margin=1in]{geometry}

* Problem 4
Find the average of function $f(\sigma) = |a_1 - a_2| + |a_3 - a_4| + |a_5 - a_6| + |a_7 - a_8|$, where $\sigma$ is a permutation of $(a_1, a_2, a_3, a_4, a_5, a_6, a_7, a_8)$.



** Solution
Method is to count the number of different distances noted by $|a_i - a_j|$. If you write 1 to 8 literally as 1, 2, 3, 4, 5, 6, 7, 8, you will note that the distance is from 1 to 7. First let's count the number of distance 1.

- distance 1 :: This is easy: pairs like $(1,2)$, $(2,3)$, ... , $(7,8)$ are distance 1. There are 7 of them.
- distance 2 :: $(1,3)$, ... , $(6,8)$. There are 6 of them.
- distance 3 :: $(1,4)$, ... , $(5,8)$. There are 5 of them.
- distance 4 :: $(1,5)$, ... , $(4,8)$. There are 4 of them.
- distance 5 :: $(1,6)$, ... , $3,8)$. There are 3 of them.
- distance 6 :: $(1,7)$, $(2,8)$. There are 2 of them.
- distance 7 :: $(1,7)$. There are 1 of them.

Each pair will appear exactly this many times: $P_6^6 \times 4 \times 2$. Explanation is: once you select a pair, e.g., $(1,2)$, you can also flip them as $(2,1)$. So that is for multiplier 2. And then you can place them in each of the 4 pairs location. And lastly, $P_6^6$ means once you fixed the selection of the pair, the remaining 6 digits will permutate this many times. So total sum of all permutations of $f(\sigma)$ is

$P_6^6 * 4 * 2 * (1*7 + 2*6 + 3*5 + 4*4 + 5*3 + 6*2 + 7*1)$. Average is given by this number divided by $P_8^8 = 40320$, which is 12.



See also: [[https://github.com/xuanni/Problems/blob/master/problem4.cpp][problem4.cpp]] for brutal force calculation. This is to verify the above solution is correct. The output of the program is below
#+BEGIN_SRC bash
brutal force method: total = 483840, number of permutations = 40320, average = 12
analytical method: average = 12
#+END_SRC

* Problem 5
Find all real \(x\) such that

\begin{equation}
log_{2x}(48\sqrt[3]{3}) = log_{3x}(162\sqrt[3]{2})
\end{equation}

** Solution
\begin{equation}
\frac{\ln(48\sqrt[3]{3})}{\ln(2) + \ln(x)} = \frac{\ln(162\sqrt[3]{2})}{\ln(3) + \ln(x)}
\end{equation}

\begin{equation}
\ln(x) = \frac{\ln(3)\cdot \ln(48\sqrt[3]{3}) - \ln(2)\cdot \ln(162\sqrt[3]{2})}{\ln(162\sqrt[3]{2}) - \ln(48\sqrt[3]{3})}
\end{equation}


\begin{eqnarray}
x &=& \exp\left[ \frac{\ln(3)\cdot \ln(48\sqrt[3]{3}) - \ln(2)\cdot \ln(162\sqrt[3]{2})}{\ln(162\sqrt[3]{2}) - \ln(48\sqrt[3]{3})}\right]\\
&=& \exp\left[\frac{\ln(3)\cdot\ln(3)-\ln(2)\cdot\ln(2)}{2(\ln(3)-\ln(2))}\right]\\
&=& \exp\left[\frac{\ln(6)}{2}\right]\\
x&=& \sqrt{6}
\end{eqnarray}


* <2024-07-21 Sun>

** Problem 5
In how many ways can 9 be written as the sum of one or more positive odd integers? (Order of the integers does not matter.)

\begin{*equation}
\begin{matrix}
 (A) 8 & (B) 6 & (C) 5 & (D) 9 & (E) 7
\end{matrix}
\end{*equation}

*** Solution
9 can only be written as sum of odd number of positive odd integers, so we have several options.
- \(9=9\)
- \(9=3+3+3\)
- \(9=1+3+5\)
- \(9=1+1+1+3+3\)
- \(9=1+1+1+1+5\)
- \(9=1+1+1+1+1+1+3\)
- \(9=1+1+1+1+1+1+1+1+1\)

So answer is (E)

** Problem 6
The sum of the digits of the positive integer \(n\) is 123. The sum of the digits of \(2n\) is 66. The digits of \(n\) include two 3s, six 7s, \(p\) 5s, \(q\) 6s and no other digits. What is \(p^2+q^2\)?

\begin{*equation}
\begin{matrix}
 (A) 106 & (B) 109 & (C) 160 & (D) 58 & (E) 72
\end{matrix}
\end{*equation}

*** Solution
Let \(d_i(n)\) be the \(i\)-th digit of n.

\begin{eqnarray}
n & = & \sum_{i=1}^{2+6+p+q} d_i(n)\cdot 10^{i-1}\\
& = & \sum_{p} 5\cdot 10^{i-1} +\sum_{q} 6\cdot 10^{i-1} +\sum_{2} 3\cdot 10^{i-1} +\sum_{6} 7\cdot 10^{i-1}
\end{eqnarray}

\begin{eqnarray}
2n & = & \sum_{p} 1\cdot 10^{i} +\sum_{q} 1\cdot 10^{i} + \sum_{q} 2\cdot 10^{i-1} +\sum_{2} 6\cdot 10^{i-1} +  \sum_{6} 1\cdot 10^{i} + \sum_{6} 4\cdot 10^{i-1}
\end{eqnarray}

Adding all digits up:

\begin{equation}
\sum_{i} d_i(n) = 5p + 6q + 2\cdot3 +6\cdot 7 = 123
\end{equation}

\begin{equation}
\sum_{i} d_i(2n) = p + q + 2q + 2\cdot6 +6\cdot 1 + 6\cdot 4 = 66
\end{equation}

We get \(p = 9\), \(q =5\), so

\begin{equation}
\boxed{p^2 + q^2 = 106}
\end{equation}

Answer is (A)
